name: Website

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run doc
    - run: touch docs/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: docs
